name: PANOS-CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/vars/**'

jobs:
  provision-panos:
    runs-on: self-hosted
    steps:
    # checkout branch
    #- uses: actions/checkout@master

    - uses: actions/checkout@v2
    - name: remove deploy if it exists
      run: rm -rf $HOME/deploy
    - name: create run directory
      run: mkdir $HOME/deploy
    - name: copy files 
      run: cp $HOME/actions-runner/_work/panos_pipeline/panos_pipeline/playbooks/pb-ip-edl.yml $HOME/deploy/pb-ip-edl.yml 
    - name: Run Ansible Playbook
      env:
        linux_hostname: ${{ secrets.LINUX_HOSTNAME }}
        linux_username: ${{ secrets.LINUX_USERNAME }}
        linux_password: ${{ secrets.LINUX_PASSWORD }}
      run: ansible-playbook $HOME/deploy/pb-ip-edl.yml --extra-vars "linux_hostname=$linux_hostname linux_password=$linux_password linux_username=$linux_username task_email=shea.john@mac.com"
    - name: remove temp deploy
      run: rm -rf $HOME/deploy 
